apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/salaboy/s1p-concerts-service:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/salaboy/s1p-concerts-service:{{.DIGEST_HEX}}"
#    artifacts:
#    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: s1p-concerts-service
        chartPath: charts/s1p-concerts-service
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/salaboy/s1p-concerts-service"
          image.tag: "{{.TAG}}"
